global using Pattrn.Builders;
global using Pattrn.Diagnostics;
global using Pattrn.Internal.Compilation;
global using Pattrn.Internal.Matching;
global using Pattrn.Internal.Storage;
global using Pattrn.Internal.Writing;
global using Pattrn.Matching;
global using Pattrn.Patterns;
global using Pattrn.Registrations;
